export const invoices = [
  {
    id: 1,
    chemical_name: "Sodium Chloride",
    vendor: "ChemCorp",
    density: "2.165",
    viscosity: "1.3",
    packaging: "Plastic Drum",
    pack_size: "25 kg",
    unit: "kg",
    quantity: 50,
  },
  {
    id: 2,
    chemical_name: "Acetone",
    vendor: "PureChem Supplies",
    density: "0.791",
    viscosity: "0.3",
    packaging: "Steel Barrel",
    pack_size: "200 L",
    unit: "L",
    quantity: 400,
  },
  {
    id: 3,
    chemical_name: "Sulfuric Acid",
    vendor: "GlobalChem",
    density: "1.84",
    viscosity: "26.7",
    packaging: "HDPE Container",
    pack_size: "50 L",
    unit: "L",
    quantity: 150,
  },
  {
    id: 4,
    chemical_name: "Hydrogen Peroxide",
    vendor: "OxidChem",
    density: "1.45",
    viscosity: "1.2",
    packaging: "Plastic Canister",
    pack_size: "20 L",
    unit: "L",
    quantity: 80,
  },
  {
    id: 5,
    chemical_name: "Ethanol",
    vendor: "GreenSolvents",
    density: "0.789",
    viscosity: "1.2",
    packaging: "Glass Bottle",
    pack_size: "5 L",
    unit: "L",
    quantity: 60,
  },
  {
    id: 6,
    chemical_name: "Sodium Hydroxide",
    vendor: "ChemicalWorks",
    density: "2.13",
    viscosity: "1.9",
    packaging: "Plastic Bucket",
    pack_size: "15 kg",
    unit: "kg",
    quantity: 45,
  },
  {
    id: 7,
    chemical_name: "Potassium Permanganate",
    vendor: "OxidChem",
    density: "2.70",
    viscosity: "N/A",
    packaging: "Plastic Bag",
    pack_size: "10 kg",
    unit: "kg",
    quantity: 30,
  },
  {
    id: 8,
    chemical_name: "Toluene",
    vendor: "PureChem Supplies",
    density: "0.866",
    viscosity: "0.59",
    packaging: "Steel Barrel",
    pack_size: "150 L",
    unit: "L",
    quantity: 300,
  },
  {
    id: 9,
    chemical_name: "Methanol",
    vendor: "GreenSolvents",
    density: "0.791",
    viscosity: "0.59",
    packaging: "Plastic Canister",
    pack_size: "10 L",
    unit: "L",
    quantity: 70,
  },
  {
    id: 10,
    chemical_name: "Acetic Acid",
    vendor: "ChemCorp",
    density: "1.049",
    viscosity: "1.22",
    packaging: "Glass Bottle",
    pack_size: "2 L",
    unit: "L",
    quantity: 50,
  },
  {
    id: 11,
    chemical_name: "Ammonium Nitrate",
    vendor: "GlobalChem",
    density: "1.725",
    viscosity: "N/A",
    packaging: "Plastic Bag",
    pack_size: "50 kg",
    unit: "kg",
    quantity: 100,
  },
  {
    id: 12,
    chemical_name: "Glycerol",
    vendor: "PureChem Supplies",
    density: "1.261",
    viscosity: "1.412",
    packaging: "Glass Bottle",
    pack_size: "10 L",
    unit: "L",
    quantity: 20,
  },
  {
    id: 13,
    chemical_name: "Benzene",
    vendor: "ChemCorp",
    density: "0.876",
    viscosity: "0.604",
    packaging: "Steel Barrel",
    pack_size: "150 L",
    unit: "L",
    quantity: 150,
  },
  {
    id: 14,
    chemical_name: "Calcium Carbonate",
    vendor: "ChemicalWorks",
    density: "2.71",
    viscosity: "N/A",
    packaging: "Plastic Bag",
    pack_size: "25 kg",
    unit: "kg",
    quantity: 75,
  },
  {
    id: 15,
    chemical_name: "Sodium Bicarbonate",
    vendor: "OxidChem",
    density: "2.20",
    viscosity: "N/A",
    packaging: "Plastic Bag",
    pack_size: "10 kg",
    unit: "kg",
    quantity: 40,
  },
];
